{% set name = "np_utils" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aa5c7ece3d1cb512d1af718aa05a5909dd47c74e5978b7c389c9b4f1a6ef804

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.0
    - future >=0.16

test:
  imports:
    - np_utils

about:
  home: https://github.com/davidmashburn/np_utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    Utilities for array and list manipulation by David Mashburn.
    Notably:
      * functions to scale arrays by integer multiples (without interpolation)
      * drawing basic graphics objects on (multi-dimensional) numpy arrays:
        * line segment, triangle, circle, and sphere
  dev_url: https://github.com/davidmashburn/np_utils

extra:
  recipe-maintainers:
    - aaronmussig
